### ISSUE TITLE
109 or 112 datasets?

### ISSUE THREAD

**Issue by firrice** [xuanmay2701/ppsn#1]
hi, I found a sentence which is "We conduct the experiment on all 112 datasets but only report the results
of 109 datasets to follow the protocol at [14]" in your paper.  But i find there have been the result of 112 problems, for 30 resamples in http://timeseriesclassification.com/results.php.  So i wonder why you choose do experiments on 109 datasets? Is that due to the reason which there was only the result of 109 peoblems in timeseriesclassification.com at the moment?

**Comment by xuanmay2701** [comment]
Hi, we conduct the experiments for all 112 datasets (you can take a look at results/ppsn_vs_sota.csv). But we only compare for 109 datasets since there some methods such as MiniRocket which only report the results for these 109.

**Comment by firrice** [comment]
> Hi, we conduct the experiments for all 112 datasets (you can take a look at results/ppsn_vs_sota.csv). But we only compare for 109 datasets since there some methods such as MiniRocket which only report the results for these 109.

Thanks for answering!
